import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import Footer from "@/components/footer";
import PostContextProvider from "@/context/postContext";
import Testimonials from "@/components/Testimonials";
import Slider from "@/components/Slider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PostContextProvider>
          <Nav />
          <Slider />
          {children}
          <Testimonials />
          <Footer />
        </PostContextProvider>
      </body>
    </html>
  );
}
